#!/bin/sh

if [ "$PKG_UPGRADE" != 1 ]; then
	uci get luci.themes.rootED >/dev/null 2>&1 || \
	uci batch <<-EOF
		set luci.themes.rootED=/luci-static/rootED
		set luci.main.mediaurlbase=/luci-static/rootED
		commit luci
	EOF
fi

exit 0
